### ISSUE TITLE
day10 #list index out of range 待解决

### ISSUE THREAD

**Issue by YAN-SU** [YAN-SU/python60lessons#28]
出现了这样的问题：
Traceback (most recent call last):
File "/Users/yansupang/Desktop/Untitled.py", line 27, in
name = d_pair[1]
IndexError: list index out of range

#在python中，list index out of range意思是列表的索引分配超出列范围。 但我上网没有看懂。所以，有关天气查找这三节课，暂时停止。先跳去学下一段先。

**Comment by YAN-SU** [comment]
出现了这样的问题：
Traceback (most recent call last):
  File "/Users/yansupang/Desktop/Untitled.py", line 27, in <module>
    name = d_pair[1]
IndexError: list index out of range

#在python中，list index out of range意思是列表的索引分配超出列范围。 但我上网没有看懂。所以，有关天气查找这三节课，暂时停止。先跳去学下一段先。
